services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bball-statsman-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: bball-statsman-backend
    environment:
      LISTEN_ADDR: ":8080"
      DB_PATH: "/app/data/statsman.json"
    expose:
      - "8080"
    volumes:
      - ./backend_data:/app/data
    restart: unless-stopped
